export const ENGLISH = {
	LANG_DIRECTION: 'left',
	SEARCH: {
		DEFAULT_SEARCH_KEYWORD: 's&p 500',
		DEFAULT_SEARCH_MSG: 'Search',
		RESULT_SEARCH_MSG: 'Results',
		IMITATING: 'Imitating',
		LEVERAGED: 'leveraged',
		SHORT: 'short',
		STOCKS: 'stocks',
		NO_RESULT_KEY_WORDS: 'No Results found for the given keywords',
		NO_RESULTS_FOR_FILTERS: 'No Results found for the given filters',
		IN_PROGRESS: 'Searching...',
		TO_MANY_RESULTS: 'Too many results found...',
		NO_NEW_FUND_TO_ADD: 'No new results the arent already in comparation',
		LOADING: 'LOADING...',
		NEW_SEARCH: 'New search',
		ADD_TO_GRAPH: 'Add to comparation',
	},

	GRAPH: { WEEK_BUTTON: 'week', MONTH_BUTTON: 'month', YEAR_BUTTON: 'year', ALL_TIME_BUTTON: 'all-time' },

	TABLE: {
		STD: 'std',
		MANAGMENT_FEE_HEADER: 'managment fee',
		OVERALL_MANAGMENT_FEE_HEADER: 'total fixed fee',
		TRUST_FEE_HEADER: 'trust fee',
		MANAGMENT_VAR_FEE_HEADER: 'variable fee',
		PRICE_HEADER: 'price',
		FUND_NUMBER_HEADER: 'paper id',
		NAME_HEADER: 'name',
		NO_DATA_HEADER: 'no info avail',
		CALCULATING_DATA_CELL: 'calculating..',
		YIELD_HEADER: 'yield of shown period',
		DELETE_BUTTON: 'delete selected',
	},
};

export const HEBREW = {
	LANG_DIRECTION: 'right',
	SEARCH: {
		DEFAULT_SEARCH_KEYWORD: 'תא 35',
		DEFAULT_SEARCH_MSG: 'חפש',
		RESULT_SEARCH_MSG: 'תוצאות',
		IMITATING: 'קרן מחקה',
		LEVERAGED: 'קרן ממונפת',
		SHORT: 'קרן בחסר',
		STOCKS: 'מניות',
		NO_RESULT_KEY_WORDS: 'לא נמצאו תוצאות העונות למילת החיפוש',
		NO_RESULTS_FOR_FILTERS: 'לא נמצאו תוצאות המתאימות לסינונים, יש לאפשר עוד סוגים או לשנות מילת חיפוש',
		IN_PROGRESS: '...מחפש',
		TO_MANY_RESULTS: 'נמצאו יותר מידי תוצאות חיפוש , אנא מקד את הפילטרים או מילות חיפוש',
		NO_NEW_FUND_TO_ADD: 'אין תוצאות חדשות שלא בהשוואה',
		LOADING: '...טוען',
		NEW_SEARCH: 'חיפוש חדש',
		ADD_TO_GRAPH: 'הוסף להשוואה',
		CHOSE_REMOVE_ALL: 'בחר / הסר הכל',
	},

	GRAPH: {
		WEEK_BUTTON: 'שבוע',
		MONTH_BUTTON: 'חודש',
		YEAR_BUTTON: 'שנה',
		ALL_TIME_BUTTON: 'הכל',
	},

	TABLE: {
		STD: 'שונות',
		MANAGMENT_FEE_HEADER: 'דמי ניהול',
		OVERALL_MANAGMENT_FEE_HEADER: 'דמי ניהול משוקלל',
		TRUST_FEE_HEADER: 'דמי נאמנות',
		MANAGMENT_VAR_FEE_HEADER: 'דמי ניהול משתנים',
		PRICE_HEADER: 'שער',
		FUND_NUMBER_HEADER: "מספר נ''ע",
		NAME_HEADER: 'שם',
		NO_DATA_HEADER: 'לא זמין',
		CALCULATING_DATA_CELL: '...מחשב',
		YIELD_HEADER: 'תשואת התקופה המוצגת',
		DELETE_BUTTON: 'הסר מההשוואה',
	},

	NAV: {
		SEARCH: 'חפש',
		CONTACT: 'צור קשר',
		FAQ: 'שאלות ותשובות',
	},
};
